dist: trusty

language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - '8'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  chrome: stable
before_install:        
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
branches:
  only:
    - master
    - /^greenkeeper/.*$/

script: "yarn run wdio"

after_success:
  
  